version: '3'
services:
  frontend:
    build:
      context: app/.
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
  backend:
    build: 
      context: api/.
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
